version: '3.8'  # Optional, can be removed

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/logs:/app/logs
    networks:
      - mynetwork
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"  # Map host port 8080 to container port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    depends_on:
      - web

volumes:
  db_data:

networks:
  mynetwork: